on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy site to Fleek
    steps:
      - uses: actions/checkout@v2
      - name: Deploy test site
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
